federation_version: 2 # Without this line, Rover uses Federation 1
subgraphs:
  iam:
    routing_url: http://localhost:4001/graphql
    schema:
      file: graphql/iam.graphql
  users:
    routing_url: http://localhost:4001/graphql
    schema:
      file: graphql/users.graphql